name: SolidFix
version: 2.1-b5
main: dev.qruet.solidfix.SolidFix
api-version: 1.13
description: Who ya gonna call? Ghost block busters! Helps resolve an issue with ghost (invisible/glitched) blocks.
website: https://www.spigotmc.org/resources/solidfix.54103/
author: qruet

commands:
  solidfix:
    aliases: [solidf, sf]
